/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LITEeditor.java
 *
 * Created on 18-ago-2009, 10.04.47
 */

package java4d.sections.editors;

import java.awt.Color;
import java.awt.Dimension;
import java4d.sections.data.LITEdata;
import java4d.sections.data.sectData;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Pierantonio
 */
public class LITEeditor extends MESHeditor {
    
    LITEdata litedata;

    /** Creates new form LITEeditor */
    public LITEeditor(sectData toEdit) {
        super(toEdit);
        //initComponents();
        litedata=(LITEdata)sdata;
        JPanel p= new JPanel();
        JPanel p1= new JPanel();
        p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));
        p1.setLayout(new BoxLayout(p1,BoxLayout.PAGE_AXIS));
        /*jPanel1.add(litedata.desc.getEditor() );
        jPanel1.add(litedata.space.getEditor() );*/
        jPanel1.add(new JLabel("Light color:"));
        
        JButton selcolorBtn = new JButton("Select light color");
        jPanel1.add(selcolorBtn);

        selcolorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color curcolor=new Color(litedata.lightColor.val[0],litedata.lightColor.val[1], litedata.lightColor.val[2]);
                curcolor=JColorChooser.showDialog(jPanel1, null, curcolor);
                if(curcolor!=null)
                {
                    litedata.lightColor.val= curcolor.getRGBColorComponents(null);
                    sdata.getOwner().getEventListener().dataChanged();
                }
            }
        });
        JLabel l=new JLabel("Light intensity:");
        l.setMinimumSize(new Dimension(10000,16));
        
        p1.add(l);
        final JSpinner jSpinner1 = new JSpinner();
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(5.0f), Float.valueOf(0.05f)));
        jSpinner1.setValue(Float.valueOf(litedata.lightMult));
        jSpinner1.setMaximumSize(new Dimension(150,(int)jSpinner1.getMinimumSize().getHeight()));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                litedata.lightMult=(Float)((SpinnerNumberModel)jSpinner1.getModel()).getValue();

            }
        });
        p1.add(jSpinner1);
        //myutil.packPanel(p, 180);
        //p1.add(new JLabel(" "));
        p.add(p1);
        jPanel1.add(p);
       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
