/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MESHimporter.java
 *
 * Created on 18-ago-2009, 19.27.00
 */

package java4d.sections.editors;

import java4d.myutil;
import java4d.sections.data.INDIdata;
import java4d.sections.data.MATEdata;
import java4d.sections.data.MESHdata;
import java4d.sections.data.VERTdata;
import java4d.sections.sectBBOX;
import java4d.sections.sectINDI;
import java4d.sections.sectMATE;
import java4d.sections.sectMESH;
import java4d.sections.sectMTLS;
import java4d.sections.sectSCEN;
import java4d.sections.sectVERT;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.java.joglutils.model.geometry.Mesh;
import net.java.joglutils.model.geometry.Model;

/**
 *
 * @author Pierantonio
 */
public class MESHimporter extends sectMaker {

    private sectMESH curmesh;
    private boolean jobdone=false;
    private Model curmod;

    /** Creates new form MESHimporter */
    public MESHimporter(java.awt.Frame parent, boolean modal,sectMESH target,Model threeDSmodel) {
        super((sectSCEN)target.getParent());
        curmesh=target;
        curmod=threeDSmodel;
        initComponents();

        setLocation(myutil.screen.width/2 - getWidth()/2 , myutil.screen.height/2 - getHeight()/2);

        jList1.setModel(new DefaultListModel());


        for(int i=0;i<curmod.getNumberOfMeshes(); i++)
        {

            ((DefaultListModel)jList1.getModel()).addElement(curmod.getMesh(i).name);
        }

    }

    public boolean isJobDone()
    {
        return jobdone;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Select the object to import:");

        jButton1.setText("Import");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jList1.getSelectedIndex()<0) 
        {
            JOptionPane.showMessageDialog(this,"Nothing selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Mesh curobj=curmod.getMesh(jList1.getSelectedIndex());
        if(curobj.numOfFaces>21485)
        {
            JOptionPane.showMessageDialog(this,"The selected object has too many faces (limit: 21485) for Panzers", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        sectVERT sectvert = new sectVERT(curmesh,curobj.numOfVerts);
        sectINDI sectindi = new sectINDI(curmesh,curobj.numOfFaces*3);
        VERTdata vdata=(VERTdata)sectvert.getSectionData();
        INDIdata idata=(INDIdata)sectindi.getSectionData();
       
        for(int i=0;i<curobj.vertices.length;i++)
        {
            vdata.vert[i].coord.val[0]=curobj.vertices[i].x;
            vdata.vert[i].coord.val[1]=curobj.vertices[i].y;
            vdata.vert[i].coord.val[2]=curobj.vertices[i].z;

            vdata.vert[i].normal.val[0]=-curobj.normals[i].x;
            vdata.vert[i].normal.val[1]=-curobj.normals[i].y;
            vdata.vert[i].normal.val[2]=-curobj.normals[i].z;
            if(curobj.hasTexture)
            {
                vdata.vert[i].textureCoord.val[0]=curobj.texCoords[i].u;
                vdata.vert[i].textureCoord.val[1]=curobj.texCoords[i].v;
            }
        }
/*
        LinkedList<int[]> tri=new LinkedList<int[]>();

        for(int i=0;i<curobj.numOfFaces;i++)
            tri.add(curobj.faces[i].vertIndex.clone());

        idata.ind = stripeConv.convertToStripe(tri);
*/
        
        for(int i=0;i<curobj.numOfFaces;i++)
        {
            idata.ind[i*3]=curobj.faces[i].vertIndex[0];
            idata.ind[i*3+1]=curobj.faces[i].vertIndex[1];
            idata.ind[i*3+2]=curobj.faces[i].vertIndex[2];
        }
        
        sectMTLS mtls=new sectMTLS(curmesh);
        sectMATE material=new sectMATE(mtls);
        mtls.setMaterial(material);
        ((MATEdata)material.getSectionData()).indiCount=idata.ind.length/3;
        ((MATEdata)material.getSectionData()).vertStart=0;
        ((MATEdata)material.getSectionData()).vertStop=vdata.vert.length-1;

        MESHdata curmeshdata=(MESHdata)curmesh.getSectionData();

        curmesh.setSubSections(new sectBBOX(curmesh), sectvert, sectindi, mtls);
        curmeshdata.space.versors[0].val[0]=1;
        curmeshdata.space.versors[1].val[1]=1;
        curmeshdata.space.versors[2].val[2]=1;
        curmeshdata.desc.val="new_Mesh";

        parentIdEditDialog ed1=new parentIdEditDialog(this, true,(MESHdata)curmesh.getSectionData());
        ed1.setVisible(true);

        int targetpos=getTargetPosition(parent);

        if(targetpos<0) return;
        ((sectSCEN)parent).addObjectAt(curmesh,targetpos );

        parent.getEventListener().structureChanged();
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
